-- pgvector 확장 활성화
CREATE EXTENSION IF NOT EXISTS vector;

-- 강의 추천용 벡터 테이블
CREATE TABLE course_vector(
                              no INT GENERATED BY DEFAULT AS IDENTITY,
                              course_no INT CONSTRAINT cv_cno_nn NOT NULL,
                              chunk_text TEXT,
                              embedding_data VECTOR(1536),
                              CONSTRAINT cv_no_pk PRIMARY KEY(no)
);
-- 코사인 유사도 검색용 인덱스
CREATE INDEX idx_vector_hnsw ON course_vector USING hnsw (embedding_data vector_cosine_ops);